version: "3.8"

services:
  api-transaction:
    build: .
    container_name: api-transaction
    volumes:
      - .:/var/www
    networks:
      - backend-network
    expose:
      - "9000"

  nginx-transaction:
    image: nginx:alpine
    container_name: nginx-transaction
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-transaction
    networks:
      - backend-network

networks:
  backend-network:
    external: true
